<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <Asset Include="$(SamplesAssetsDir)\sponza\spnza_bricks_a_diff.png" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\common\SampleBase\SampleBase.csproj" />
        <ProjectReference Include="..\..\common\AssetPrimitives\AssetPrimitives.csproj" />
        <ProjectReference Include="..\..\common\AssetProcessor\AssetProcessor.csproj">
            <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
            <SkipGetTargetFrameworkProperties>true</SkipGetTargetFrameworkProperties>
        </ProjectReference>
    </ItemGroup>

</Project>
