changelog:
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: Breaking Changes
      labels:
        - breaking
    - title: Features & Improvements
      labels:
        - enhancement
    - title: Bug Fixes
      labels:
        - bug
    - title: Documentation
      labels:
        - documentation
    - title: Internal
      labels:
        - refactor
    - title: Dependencies
      labels:
        - dependencies
    - title: Other Changes
      labels:
        - "*"
