#version 450

struct IndirectDrawIndexedArguments
{
    uint IndexCount;
    uint InstanceCount;
    uint FirstIndex;
    int VertexOffset;
    uint FirstInstance;
};

layout(std430, set = 0, binding = 0) readonly buffer Params
{
    IndirectDrawIndexedArguments field_Params[];
};

layout(std430, set = 0, binding = 1) buffer Destination
{
    IndirectDrawIndexedArguments field_Destination[];
};

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

void main()
{
    uint index = gl_GlobalInvocationID.x;
    field_Destination[index] = field_Params[index];
}
