<Project>

    <PropertyGroup>
        <IsPackable>false</IsPackable>
        <RootNamespace>NeoVeldrid.Samples</RootNamespace>
    </PropertyGroup>

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <LangVersion>latest</LangVersion>
        <Nullable>disable</Nullable>
        <UseArtifactsOutput>true</UseArtifactsOutput>
    </PropertyGroup>

</Project>
